export type PermissionsType = typeof PERMISSION_TYPES[keyof typeof PERMISSION_TYPES];

type RolePermissions = {
  ADMIN: PermissionsType[],
  FACILITY_STAFF: PermissionsType[]
}

export const PERMISSION_TYPES = {
  REGISTER_FACILITY: "REGISTER_FACILITY",
  EDIT_FACILITY: "EDIT_FACILITY",
  DELETE_FACILITY: "DELETE_FACILITY",
  ASSIGN_STAFF: "ASSIGN_STAFF",
  FETCH_STAFF: "FETCH_STAFF",
  DISMISS_STAFF: "DISMISS_STAFF",
  FETCH_FACILITY: "FETCH_FACILITY",

  FETCH_RESOURCE: "FETCH_RESOURCE",
  EDIT_RESOURCE: "EDIT_RESOURCE",

  REGISTER_STAFF_ACC: "REGISTER_STAFF_ACC",
} as  const

export const ROLE_PERMISSIONS: RolePermissions = {
  ADMIN: Object.values(PERMISSION_TYPES), // MEANS ADMIN HAS ALL THE PERMISSIONS
  FACILITY_STAFF: [
    PERMISSION_TYPES.EDIT_FACILITY,
    PERMISSION_TYPES.FETCH_STAFF,
    PERMISSION_TYPES.FETCH_FACILITY,
    PERMISSION_TYPES.FETCH_RESOURCE,
    PERMISSION_TYPES.EDIT_RESOURCE,
  ],
} as RolePermissions